### ISSUE TITLE
Overwiew is unclear

### ISSUE THREAD

**Issue by GrosSacASac** [EtherDream/QuickReader#2]
Maybe for you it is obvious, but I would write it explicitly:

**Cursor based stream reader to extract data with byte level precision from a stream in a known format .**

Also the following is unclear:

const id   = reader.u32() ?? await A

Does it read the next 32 bits as an unsigned integer ? If yes it should also be written in the doc.

**Comment by EtherDream** [comment]
u: unsigned integer, i: signed integer, f: float, be: big endian.

The doc has been updated.
